name: pydata-berlin-2019
channels:
- conda-forge
dependencies:
- ipyleaflet
- jupyterlab=1
- nbdime
- pip
- python=3.7
- pip:
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupyterlab-quickopen
  - jupyterlab_sql
  - sidecar

